name:                HaskellLabs
version:             0.1.0.0
github:              "Adrjanjan/HaskellLabs"
license:             BSD3
author:              "Adrian Janakiewicz"
maintainer:          ""
copyright:           "2019 Adrian Janakiewicz"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Adrjanjna/HaskellLabs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HaskellLabs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellLabs

tests:
  HaskellLabs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellLabs
